### ISSUE TITLE
Patch for Windows DirectSound and WMME UTF-8 device names

### ISSUE THREAD

**Issue by PortAudio-admin** [PortAudio/portaudio#224]
*Issue created by @RossBencina*

from Tobias Erichsen

Patch in attachment

Original discussion thread here:

http://comments.gmane.org/gmane.comp.audio.portaudio.devel/10876

**Comment by MichalPetryka** [comment]
Still experiencing MME and DS giving ANSI instead of UTF-8 on current master, MME also seems to truncate device names to 31 characters.

**Comment by dechamps** [comment]
@MichalPetryka the MME 31-char limitation [seems to be a limitation of MME itself](https://stackoverflow.com/questions/1429143/get-the-full-audio-device-name-from-windows) so I doubt anything can be done about it.

**Comment by MichalPetryka** [comment]
Noticed it while looking at the code.

Fixing DS seems rather easy, as fair as i can see changing CP_ACP to CP_UTF8 in lines 412 and 416 would be enough since that already gets the text in WCHARs.

With MME the thing seems a bit more complicated due to to it using TCHARs, and WINAPI not having a direct ANSI -> UTF-8 conversion, which would force CopyTCharStringToUtf8CString to allocatre a temp buffer, convert to WCHARs in it and then convert back to UTF-8 in the output buffer and TCharStringLen would also need to do the same in order to get the proper required length.
Since TCharStringLen seems to be only used with CopyTCharStringToUtf8CString, it could probably get removed and CopyTCharStringToUtf8CString could be changed to allocate the output buffer internally in order to avoid allocating a temp WCHAR buffer twice.

**Comment by RossBencina** [comment]
@MichalPetryka feel free to submit a patch for one or both of these issues -- especially if you have a setup that outputs non-ASCII characters with WMME or DirectSound APIs. I have no way to test here.

**Comment by MichalPetryka** [comment]
I'm wondering if it'd maybe be a better solution to manually define UNICODE with MME in order to force TCHARs to become WCHARs, otherwise we're forced to use ANSI which can incorrectly store some characters and to convert to WCHARs like i described which has a performance cost.

**Comment by RossBencina** [comment]
Related #200
