### ISSUE TITLE
portaudio is not supported in macOS SDK 11.0

### ISSUE THREAD

**Issue by jmelas** [PortAudio/portaudio#350]
Newest version of Xcode 12.2 comes with new SDK v11.0 for macOS 11 Big Sur.
Portaudio build find (with the already known deprecation warnings) but in the runtime it fails
with the following message:
"This application, or a library it uses, is using the deprecated Component Manager for hosting Audio Components. This is not supported when rebuilding against the 10.16 or later SDK. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h."

**Comment by philburk** [comment]
Thanks for alerting us to this.  This bug is a subset of #218. We had given #218 a low priority because we wanted to keep compatibility with older OS versions. But if PortAudio is failing with Mac OS 11.0 then it needs to be fixed ASAP. I will close this bug as a duplicate and bump the priority of #218.
