### ISSUE TITLE
"_WIN32_WINNT" redefined warning in pa_win_ds.c

### ISSUE THREAD

**Issue by RossBencina** [PortAudio/portaudio#549]
@mgeier wrote:
There is a warning about another preprocessor definition:

    src/hostapi/dsound/pa_win_ds.c:54:0: warning: "_WIN32_WINNT" redefined
     #define _WIN32_WINNT 0x0400 /* required to get waitable timer APIs */
     ^
    [...]/mxe/usr/i686-w64-mingw32.static/include/_mingw.h:233:0: note: this is the location of the previous definition
     #define _WIN32_WINNT 0x502

@dmitrykos wrote:

May be it makes sense to adjust it to:

    #if !defined(_WIN32_WINNT) || (_WIN32_WINNT < 0x0400)
        #undef _WIN32_WINNT
        #define _WIN32_WINNT 0x0400 /* required to get waitable timer APIs */
    #endif

@RossBencina wrote:

I am not sure about redefining `_WIN32_WINNT ` if it is already defined. I think it is better to move the define further up the file before any include statements.

**Comment by dmitrykos** [comment]
@RossBencina, the warning comes due this line: https://github.com/PortAudio/portaudio/blob/67caa13f19251f099c0894813964d6ad7315fa6b/src/hostapi/dsound/pa_win_ds.c#L54

MinGW (W64) is defining `_WIN32_WINNT` and thus the conflict happens. It could also be defined by the user globally in some project settings, therefore my proposed construct defines `0x0400` only if it is not defined or if the defined value is lower than `0x0400` (here works `#undef _WIN32_WINNT` line).

**Comment by RossBencina** [comment]
@dmitrykos I don't think that changes my suggestion that it should be done at the top of the file, prior to any `#include` directives.

Does MinGW define `_WIN32_WINNT` unconditionally?

**Comment by RossBencina** [comment]
MSDN info about `_WIN32_WINNT` for reference: https://docs.microsoft.com/en-us/windows/win32/winprog/using-the-windows-headers?redirectedfrom=MSDN

**Comment by dmitrykos** [comment]
@RossBencina in case of MinGW-W64 compiler the `_WIN32_WINNT` is defined in `_mingw.h` when compiler is targeted to some Windows version by default during its assembly:
https://github.com/mirror/mingw-w64/blob/master/mingw-w64-headers/crt/_mingw.h.in

Therefore during compilation it will throw the warning which can be seen in this comment:
https://github.com/PortAudio/portaudio/issues/354#issuecomment-815609627

To my view the best would be to check if `_WIN32_WINNT` is defined and if its version is lower then redefine to `0x0400` otherwise do not override. It looks like a reliable approach and will eliminate this warning.

**Comment by RossBencina** [comment]
Phil and I think that it makes sense to use Dmitry's suggestion, and put it at the top of the file.
