### ISSUE TITLE
error callback needed when stream is disconnected or fails

### ISSUE THREAD

**Issue by philburk** [PortAudio/portaudio#600]
PortAudio should be able to callback to the app  if an internal error happens in a stream.
These errors would include disconnection events caused by unplugging headphones.

Something like the error callback in AAudio on Android.
https://developer.android.com/ndk/reference/group/audio#group___audio_1gaebf5b0cd3a30c257c6e66c037c229bab

Should the app be required to stop and/or close the stream after this callback? This has been a source of complex race conditions in AAudio.

**Comment by RossBencina** [comment]
Possibly a duplicate of #143

We already have a callback when the stream finishes, if there was a way to indicate that an error happened that could possibly be reused.

Yes, StopStream should be called after a stream becomes inactive due to an error condition. We have a state machine that indicates when the stream should be stopped by the client, any async error reporting should be integrated with that.:

http://portaudio.com/docs/proposals/010-ClarifyStreamStateMachine.html

**Comment by philburk** [comment]
Yes, DUP of #143
